version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  migration:
    image: flyway/flyway:9:22:3
    command: -community -url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=admin -connectRetries=60 migrate
    volumes:
      - ./db-schema/migration/sql:/flyway/sql
    depends_on:
      - postgres